MyEnum drop/2 , drop_every/2, drop_while/2 구현
27672f75-6a84-45d8-808e-754f96daa437/my_enum pull request #9
Opened 2022-07-31 14:47 UTC by twozeronine

drop 함수 구현도중 reverse에서 reverse 재귀중에 빈 리스트인 [ ] 를 패턴매칭 하지 못하는 예외사항을 발견하여 수정하였습니다 !

2022-07-31 23:34 UTC, rudebono requested changes

2022-07-31 23:34 UTC, rudebono commented on lib/my_enum.ex
> +  def reverse(list, tail \\ [])
```elixir
MyEnum.reverse([], [1,2,3])
```

해당 케이스가 실패합니다.

2022-07-31 23:46 UTC, rudebono requested changes
```elixir
def drop([], _amount), do: []

def drop(list, 0), do: list

def drop(list, amount) when amount < 0 do
  list
  |> reverse()
  |> drop(amount * -1)
  |> reverse()
end

def drop([_h | t], amount), do: drop(t, amount - 1)
```

제가 작성한 `drop` 입니다.
본인이 작성한 함수와 다른점을 찾고 코드 작성할때 생각하는 마인드를 한층 더 업그레이드 해보세요.
지금은 코드를 작성하는 생각을 넓히는 과정입니다.
돌아가는 코드를 빠르게 작성하는건 의미가없습니다.

2022-07-31 23:46 UTC, rudebono commented on lib/my_enum.ex
> +      false -> MyEnum.reverse(list)
같은 모듈에 있는 함수는 `MyEnum.reverse`에서 모듈명을 생략할 수 있습니다.
`reverse`만 사용하면 되며, 만약에 모듈명을 입력해야하는 상황이 있다면,
`__MODULE__.reverse()` 라고 하면됩니다. `__MODULE__`은 현재 모듈명을 약칭합니다.

2022-08-01 00:10 UTC, twozeronine commented on lib/my_enum.ex
> +  def reverse(list, tail \\ [])
수정하겠습니다

2022-08-01 00:11 UTC, twozeronine commented on lib/my_enum.ex
> +      false -> MyEnum.reverse(list)
넵 참고하겠습니다

2022-08-01 02:21 UTC, rudebono requested changes

2022-08-01 02:21 UTC, rudebono commented on lib/my_enum.ex
> +  def reverse([h | t], tail) when is_list(tail), do: reverse(t, [h], tail)
타입 체크를 위해 `when` 을 굳이 사용하지 않아도 됩니다.
다른 프로그래밍 언어 같은 경우는 로직상 오류가 발생하면,
프로그램이 터져버려 심각한 피해를 입힐 수 있습니다만,
Erlang OTP / Elixir 에서는 로직이 실패하여도, 가상머신 자체가 터지지않기 때문에
그냥 실패하게 냅두면 됩니다.
iex 콘솔도 하나의 Erlang 프로세스이며, 로직 실패시 프로세스가 터지고, 다시 새로운 프로세스가 생성되어 복구가 되어지게 됩니다.
이걸 "Let It Crash" 라고 하는데 (실패하게 냅둬라),
https://medium.com/pragmatic-programmers/understanding-let-it-crash-f206947f3486 를 참고하면 좋을듯싶네요.

reverse는 아래와 같이 작성할 수 있습니다.
엘릭서 함수를 잘 작성하는 팁은,
마지막 경우의 수를 맨 앞 함수 정의에 다가 두면 쉽게 풀어집니다.
리스트가 빈 [] 인 경우, amount가 0인경우 이런식으로...

```elixir
def reverse([]), do: []
def reverse([h | t]), do: reverse(t) ++ [h]
def reverse(list, tail \\ []), do: reverse(list) ++ tail
```

2022-08-01 02:25 UTC, twozeronine commented on lib/my_enum.ex
> +  def reverse([h | t], tail) when is_list(tail), do: reverse(t, [h], tail)
default 정의 부분이 꼭 앞에 올 필요가 없네요 !
 참고해서 다시 수정하겠습니다 !

2022-08-01 02:38 UTC, rudebono commented on lib/my_enum.ex
> +  def reverse([h | t], tail) when is_list(tail), do: reverse(t, [h], tail)
넵 default는 굳이 맨 앞에 둘 필요는 없습니다.
reverse 이외 다른 함수들도 고칠만한게 보이는데 수정해보세용

2022-08-01 03:28 UTC, rudebono approved these changes
LGTM

2022-08-01 03:29 UTC, merged